# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: server

on:
  push:
    branches:
      - master
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Ingresar a la carpeta
        run: cd backend

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "HRKU-cd6eb0d1-fcac-4d8c-84fe-63e7ff699ad1"
          heroku_app_name: "server11"
          heroku_email: "maximo.98@hotmail.com"
          build_dir: "server"
      - name: Saliendo de la carpeta
        run: cd ..
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Ingresar a la carpeta
        run: cd client
      - name: Install dependencies
        run: npm install --prefix client
      - name: Build
        run: npm run build --prefix client
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "HRKU-cd6eb0d1-fcac-4d8c-84fe-63e7ff699ad1"
          heroku_app_name: "iniciosesion"
          heroku_email: "maximo.98@hotmail.com"
          build_dir: "client/build"
      - name: Salir de la carpeta
        run: cd ..
